from gempy_engine.config import *

DEFAULT_BACKEND = AvailableBackends.aesara

DEBUG_MODE = DEBUG_MODE
OPTIMIZE_MEMORY = OPTIMIZE_MEMORY
TENSOR_DTYPE = TENSOR_DTYPE
LINE_PROFILER_ENABLED = LINE_PROFILER_ENABLED
